export const campingPlace = [
  {
    id: 1,
    name: "캠프 그라운드 화온",
    price: "40,000~",
    people: "기준2인/최대6인",
    location: "충북 논산시",
    type: "오토캠핑",
    rating: 5.0,
    reviews: 123,
    heart: 89,
    reservations: 168,
    img: "https://campingagains3.s3.ap-northeast-2.amazonaws.com/small_C1_d5d87fe452.jpg",
  },
  {
    id: 2,
    name: "평창힐링캠핑",
    price: "60,000~",
    people: "기준4인/최대8인",
    location: "강원 평창군",
    type: "글램핑",
    rating: 2,
    reviews: 98,
    heart: 189,
    reservations: 200,
    img: "https://campingagains3.s3.ap-northeast-2.amazonaws.com/small_C1_d5d87fe452.jpg",
  },
  {
    id: 3,
    name: "가평 리버뷰 캠핑장",
    price: "55,000~",
    people: "기준2인/최대6인",
    location: "경기 가평군",
    type: "카라반",
    rating: 3,
    reviews: 110,
    heart: 91,
    reservations: 140,
    img: "https://campingagains3.s3.ap-northeast-2.amazonaws.com/small_C1_d5d87fe452.jpg",
  },
  {
    id: 4,
    name: "제주 오션뷰 캠핑",
    price: "70,000~",
    people: "기준4인/최대8인",
    location: "제주 제주시",
    type: "오토캠핑",
    rating: 4,
    reviews: 89,
    heart: 39,
    reservations: 190,
    img: "https://campingagains3.s3.ap-northeast-2.amazonaws.com/small_C1_d5d87fe452.jpg",
  },
  {
    id: 5,
    name: "남해 해양 캠핑장",
    price: "45,000~",
    people: "기준2인/최대6인",
    location: "경남 남해군",
    type: "차박",
    rating: 1,
    reviews: 77,
    heart: 221,
    reservations: 115,
    img: "https://campingagains3.s3.ap-northeast-2.amazonaws.com/small_C1_d5d87fe452.jpg",
  },
];
