/*****************************
 * 	이미지 불러오기
 */
import prev from "/src/assets/svg/arrowNext.svg";
import heart from "/src/assets/svg/heart.svg";

export const saveIcon = {
  prev,
  heart,
};

/*****************************
 * 	찜목록 데이터
 */
export const saveData = [
  {
    wish: true,
    id: 0,
    campImage: "/src/assets/image/detailImg-1.png",
    campName: "캠프그라운드 화온",
    price: 40000,
    addr: "충남 아산시 영인면 고룡산로 512-37",
    standardNum: 4,
    maxNum: 6,
    overCharge: 10000,
    phoneNumber: 123456789,
  },
  {
    wish: true,
    id: 1,
    campImage: "/src/assets/image/detailImg-2.png",
    campName: "파이브이모션",
    price: 50000,
    addr: "경기 용인시 처인구 백암면 고안리 51-5",
    standardNum: 3,
    maxNum: 5,
    overCharge: 20000,
    phoneNumber: 36732572,
  },
  {
    wish: true,
    id: 2,
    campImage: "/src/assets/image/detailImg-3.png",
    campName: "캠프그라운드 화온",
    price: 40000,
    addr: "충남 아산시 영인면 고룡산로 512-37",
    standardNum: 4,
    maxNum: 6,
    overCharge: 10000,
    phoneNumber: "03136732572",
  },
  {
    wish: true,
    id: 3,
    campImage: "/src/assets/image/detailImg-4.png",
    campName: "파이브이모션",
    price: 50000,
    addr: "경기 용인시 처인구 백암면 고안리 51-5",
    standardNum: 3,
    maxNum: 5,
    overCharge: 20000,
    phoneNumber: 0o3136732572,
  },
  {
    wish: true,
    id: 4,
    campImage: "/src/assets/image/detailImg-1.png",
    campName: "캠프그라운드 화온",
    price: 40000,
    addr: "충남 아산시 영인면 고룡산로 512-37",
    standardNum: 4,
    maxNum: 6,
    overCharge: 10000,
    phoneNumber: 0o3136732572,
  },
  {
    wish: true,
    id: 5,
    campImage: "/src/assets/image/detailImg-2.png",
    campName: "파이브이모션",
    price: 50000,
    addr: "경기 용인시 처인구 백암면 고안리 51-5",
    standardNum: 3,
    maxNum: 5,
    overCharge: 20000,
    phoneNumber: 0o3136732572,
  },
  {
    wish: true,
    id: 6,
    campImage: "/src/assets/image/detailImg-3.png",
    campName: "캠프그라운드 화온",
    price: 40000,
    addr: "충남 아산시 영인면 고룡산로 512-37",
    standardNum: 4,
    maxNum: 6,
    overCharge: 10000,
    phoneNumber: 0o3136732572,
  },
  {
    wish: true,
    id: 7,
    campImage: "/src/assets/image/detailImg-4.png",
    campName: "파이브이모션",
    price: 50000,
    addr: "경기 용인시 처인구 백암면 고안리 51-5",
    standardNum: 3,
    maxNum: 5,
    overCharge: 20000,
    phoneNumber: 0o3136732572,
  },
  {
    wish: true,
    id: 8,
    campImage: "/src/assets/image/detailImg-4.png",
    campName: "파이브이모션",
    price: 50000,
    addr: "경기 용인시 처인구 백암면 고안리 51-5",
    standardNum: 3,
    maxNum: 5,
    overCharge: 20000,
    phoneNumber: 0o3136732572,
  },
];
